name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    
    - name: Run pre-build commands
      run: |
        echo "Running pre-build commands"
        ln -s xerhab/{Dockerfile,.dockerignore} .
        DATE=$(date "+%Y%m%d")
        echo "DATE=$DATE" >> $GITHUB_ENV
    
    - name: Build and publish a Docker image for ${{ github.repository }}
      uses: macbre/push-to-ghcr@master
      with:
        image_name: ${{ github.repository }}  # it will be lowercased internally
        github_token: ${{ secrets.GITHUB_TOKEN }}
        image_tag: ${{ env.DATE }}.${{ github.run_number }}
