name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    
    - name: Run pre-build commands
      run: |
        echo "Running pre-build commands"
        ln -s docker/{nvidia/Dockerfile,.dockerignore} .
        DATE=$(date "+%Y%m%d")
        echo "DATE=$DATE" >> $GITHUB_ENV
    
    - name: Build Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository }}:${{ env.DATE }}.${{ github.run_number }} -t ghcr.io/${{ github.repository }}:latest .
    
    - name: Login to GitHub Container Registry
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    
    - name: Push Docker image
      run: docker push --all-tags ghcr.io/${{ github.repository }}:${{ env.DATE }}.${{ github.run_number }}
